services:

  user-service:
    build: ./src/UserService
    container_name: user-service
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - powerport

  station-service:
    build: ./src/StationService
    container_name: station-service
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - powerport

  billing-service:
    build: ./src/BillingService
    container_name: billing-service
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - powerport

  provider-service:
    build: ./src/ProviderService
    container_name: provider-service
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - powerport

  data-tracking-service:
    build: ./src/DataTrackingService
    container_name: data-tracking-service
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - powerport

  reviews-service:
    build: ./src/ReviewsService
    container_name: reviews-service
    ports:
      - "5006:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - powerport

  frontend:
    build: ./frontend/web
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - powerport

networks:
  powerport:
    driver: bridge
